language: generic

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

os: linux

# The apt packages below are needed for sphinx builds. A full list of
# packages that can be included can be found here:
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
    apt:
        packages:
            - gfortran

env:
    global:
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=1.12
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='scipy scikit-learn<0.19 nose matplotlib pymc'
        - PIP_DEPENDENCIES='astroML_addons'
        - DEBUG=true
        - MAIN_CMD='nosetests'
        - SETUP_CMD='astroML'

matrix:
    fast_finish: true

    include:
        - env: NUMPY_VERSION=1.11

        - env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.10
               MAIN_CMD='make' SETUP_CMD='test-code test-doc'

        - env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.9

        - env: PYTHON_VERSION=2.7


install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python setup.py install

script:
    - $MAIN_CMD $SETUP_CMD
